### PR TITLE
Minor Storybook rc upgrade and associated deps and linting fixes

### LINKED ISSUE #486: ApplicationSection and ApplicationStatus stories throw Storybook error
Originally flagged by @software-project, and easy to duplicate locally:

```
WARNING in ./src/atoms/ApplicationStatus.stories.tsx
Module build failed (from /Users/bk3c/projects/exygy/bloom/node_modules/@storybook/source-loader/dist/index.js):
TypeError: string.toLowerCase is not a function
    at sanitize (/Users/bk3c/projects/exygy/bloom/node_modules/@storybook/csf/dist/index.js:27:17)
    at handleADD (/Users/bk3c/projects/exygy/bloom/node_modules/@storybook/source-loader/dist/abstract-syntax-tree/parse-helpers.js:175:15)
[...]
```

This one is pretty bizarre, and I can't figure it out after a couple hours of looking. There's nothing conspicuously different about these two stories compared to other similar ones, and the errors remain even after a number of attempts to simplify the stories down to a more basic case. 🤷

### PR DESCRIPTION
**Pull request by bk3c**
This started out as an effort to fix #486, which I did not make any headway on, but at least I fixed ~60 linter complaints so I figured I would make a PR out of it.

NB: The ApplicationSection and ApplicationStatus stories have both been cut down in an attempt to debug them, so they'll need to be restored once we figure that part out and before we merge this.

### CODE REVIEW

File: apps/public-reference/layouts/application.tsx [hunk 1]
```diff
@@ -1,6 +1,6 @@
 import * as React from "react"
 import Head from "next/head"
-import t from "@bloom-housing/ui-components/src/helpers/translator"
+import { t } from "@bloom-housing/ui-components/src/helpers/translator"
```
Comment (bencpeters) [inline apps/public-reference/layouts/application.tsx:3]: While we're changing this, probably better as:

```suggestion
import { t } from "@bloom-housing/ui-components"
```

File: shared/ui-components/src/atoms/ApplicationStatus.tsx [hunk 2]
```diff
@@ -1,9 +1,9 @@
 import * as React from "react"
 import moment from "moment"
-import t from "@bloom-housing/ui-components/src/helpers/translator"
+import { t } from "@bloom-housing/ui-components/src/helpers/translator"
```
Comment (bencpeters) [inline shared/ui-components/src/atoms/ApplicationStatus.tsx:3]: This should be a relative import, since we're inside the `ui-components` package:

```suggestion
import { t } from "../helpers/translator"
```

File: shared/ui-components/src/lists/PreferencesList.tsx [hunk 3]
```diff
@@ -1,6 +1,6 @@
 import * as React from "react"
 import { Preference, PreferenceLink } from "@bloom-housing/core"
-//import t from "@bloom-housing/ui-components/src/helpers/translator"
+//import { t } from"@bloom-housing/ui-components/src/helpers/translator"
```
Comment (bencpeters) [inline shared/ui-components/src/lists/PreferencesList.tsx:3]: If this is unused, just remove? It's easy enough to add back in later.

File: shared/ui-components/src/page_components/UnitTables.tsx [hunk 4]
```diff
@@ -3,7 +3,7 @@ import { nanoid } from "nanoid"
 import { MinMax, UnitSummary, Unit } from "@bloom-housing/core"
 
 import { BasicTable } from "../tables/BasicTable"
-import t from "../../src/helpers/translator"
+import { t } from "../../src/helpers/translator"
```
Comment (bencpeters) [inline shared/ui-components/src/page_components/UnitTables.tsx:6]: Pedantic, but this should be:

```suggestion
import { t } from "../helpers/translator"
```

File: shared/ui-components/src/page_components/listing/AdditionalFees.tsx [hunk 5]
```diff
@@ -1,6 +1,6 @@
 import * as React from "react"
 import { Listing } from "@bloom-housing/core"
-import t from "@bloom-housing/ui-components/src/helpers/translator"
+import { t } from "@bloom-housing/ui-components/src/helpers/translator"
```
Comment (bencpeters) [inline shared/ui-components/src/page_components/listing/AdditionalFees.tsx:3]: Another relative import (we're inside `ui-components`):

```suggestion
import { t } from "../../helpers/translator"
```

File: shared/ui-components/src/page_components/listing/ListingsList.tsx [hunk 6]
```diff
@@ -1,13 +1,13 @@
...
 import { Listing } from "@bloom-housing/core"
-import LinkButton from "../../atoms/LinkButton"
+import { LinkButton } from "../../atoms/LinkButton"
 import { groupNonReservedAndReservedSummaries } from "../../helpers/tableSummaries"
 import {
   GroupedTable,
   GroupedTableGroup,
 } from "@bloom-housing/ui-components/src/tables/GroupedTable"
-import t from "@bloom-housing/ui-components/src/helpers/translator"
+import { t } from "@bloom-housing/ui-components/src/helpers/translator"
```
Comment (bencpeters) [inline shared/ui-components/src/page_components/listing/ListingsList.tsx:10]:
```suggestion
import { t } from "../../helpers/translator"
```

File: apps/public-reference/layouts/application.tsx (hunk 1 above)
Comment (bk3c) [reply apps/public-reference/layouts/application.tsx:3]: combined with next import statement instead

File: shared/ui-components/src/page_components/UnitTables.tsx (hunk 4 above)
Comment (bk3c) [reply shared/ui-components/src/page_components/UnitTables.tsx:6]: and the next two lines, too
